name: EGM722_Assignment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - geopandas
  #- cartopy
  - notebook
  #- rasterio
  #- pyepsg
  - folium
  #- collections
  - shapely
  - matplotlib